set -g mouse on

setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

set-option -g history-limit 100000
set -g status-right '%H:%M:%S %d-%b-%y'
set-option -g status-interval 1

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
